[package]
name = "test_storage"
version = "0.0.1"
edition = "2018"
publish = false

[dependencies]
keys = { path = "../keys" }
tikv_util = { path = "../tikv_util" }
tikv = { path = "../../" }
test_raftstore = { path = "../test_raftstore" }
kvproto = { git = "https://github.com/Fullstop000/kvproto.git", default-features = false, branch = "batch_resolve_locks" }
futures = "0.1"
